### ISSUE TITLE
Doesn't work in Sublime 3 Alpha

### ISSUE THREAD

**Issue by chapati23** [abrookins/OpenSearchResult#3]
tried to install both as a normal package and via sublime package control. both to no effect. thoughts?

**Comment by abrookins** [comment]
Thanks for the report. Unfortunately, I won't have access to ST 3 until the developer opens it to the public.

**Comment by chapati23** [comment]
Not a registered user? http://www.sublimetext.com/3

I got it to work through keybindings btw. No need for a plugin anymore :)
Just added this to my keymap:

{ "keys": ["g","o"], "command": "next_result", "context": [{ "key": "setting.command_mode", "operand": true}] }

Did the trick.

On Mar 27, 2013, at 05:15 AM, Andrew Brookins notifications@github.com wrote:

Thanks for the report. Unfortunately, I won't have access to ST 3 until the developer opens it to the public.
