### ISSUE TITLE
Does nothing on Sublime 3

### ISSUE THREAD

**Issue by lmartins** [abrookins/OpenSearchResult#9]
Not sure what is happening but on my install it does nothing. It also doesn't create a settings option in Sublime's dropdown menu.

Does it only work in Vintage Mode?

Thanks.

**Comment by joshuapinter** [comment]
Hey @lmartins, I never tested this on Sublime 3 but one of the maintainers of Package Control said it worked just fine.

I only use it in Vintage Mode on Sublime Text 2. Can you try using it Vintage Mode and see if it works?

**Comment by abrookins** [comment]
Thank you for the report. The plugin should also work in non-Vintage mode with the Control+Enter key combo. 

What OS are you using? I think I only created a default settings file for OS X, so that may be the issue if you're using another OS. I'll take a look as soon as I can.

**Comment by lmartins** [comment]
Oh, Control+Enter is just what I was looking for. So, so useful. 
Thank you Andrew
